### PR TITLE
Replace mod with subtraction

### PR DESCRIPTION
**Pull request by zxyil**
mod is slow

### CODE REVIEW

**Comment by wesley-a-leung** [comment]
Brackets are actually not needed because of order of operations

**Review by crackersamdjam — CHANGES_REQUESTED** [review]
no. modding once outside the brackets is enough.

**Comment by wesley-a-leung** [comment]
I think this change would still be beneficial due to the significant performance increase.

**Comment by wesley-a-leung** [comment]
Modding once outside the brackets is subject to overflow issues for large mods.

**Comment by ac615223s5** [comment]
:chadliam:

**Comment by crackersamdjam** [comment]
finish the pr, chadliam @zxyil :blobree:

**Comment by ac615223s5** [comment]
🐒

**Comment by wesley-a-leung** [comment]
I'm not sure this PR needs any more changes. All the changes proposed in the comments are either cosmetic (and arguable would subtract from readability), or would result in overflow issues.

**Comment by ac615223s5** [comment]
I don't think this pr is even necessary but idk lol

**Comment by ac615223s5** [comment]
actually I don't think this template is even necessary 🙈

**Comment by ac615223s5** [comment]
because it doesn't work for a lot of different hashing problems

**Comment by ac615223s5** [comment]
idk

**Comment by crackersamdjam** [comment]
If the multiplication doesn't overflow, I'm not worried about the addition overflowing. I don't think it's worth modding twice.

**Comment by wesley-a-leung** [comment]
> If the multiplication doesn't overflow, I'm not worried about the addition overflowing. I don't think it's worth modding twice.

Ahh I suppose you're correct. I guess a short proof wouldn't hurt:

Suppose s is instead an unsigned integer array rather than a string with the mod being at most 2^32. Then`s[s[s.size()-1-i]*p[i]]` could be at most (2^64 - 1) - (2^32 - 1) - (2^32 - 1) and `lv` will be at most 2^32 - 1. Thus, `lv = (s[s.size()-1-i]*p[i] % mod) + lv;` will be at most `(2^64 - 1) - (2^32 - 1)`. A similar proof can be done for signed integers with even stronger bounds.

I suppose this could potentially bring up the question about someone uses a custom integer type that doesn't conform to powers of 2 but perhaps that's too special of a case to bother considering for this template?

**Comment by crackersamdjam** [comment]
Thanks Wesley :monkey:

**Pull request closed without merging**
