### PR TITLE
Create sqrt_bsearch.py

### PR DESCRIPTION
**Pull request by RuhanLi**

### CODE REVIEW

**Comment by crackersamdjam** [comment]
When would anyone need this?

**Comment by jacklee1792** [comment]
I believe this is very useful, because you can use the binary search technique and apply it to find the square root of a number.

**Comment by jacklee1792** [comment]
Also, if you can find the square root of a number, you can also multiply it by itself to get the original number (this is called an inverse function, by the way)

**Comment by jacklee1792** [comment]
Also, if you are checking for factors of a number, you only have to loop to the square root because of the number theorem. And then, you can get the factors. This will take O(square root n) time (big Oh-notation), which is very fast actually.

**Comment by ac615223s5** [comment]
so uh basically essentially you would need this function to find the square root of a number

**Comment by ac615223s5** [comment]
The principal square root function f(x) = √x (usually just referred to as the "square root function") is a function that maps the set of nonnegative real numbers onto itself. In geometrical terms, the square root function maps the area of a square to its side length.

**Comment by ac615223s5** [comment]
The square root of x is rational if and only if x is a rational number that can be represented as a ratio of two perfect squares. The square root function maps rational numbers into algebraic numbers, the latter being a superset of the rational numbers.

**Comment by ac615223s5** [comment]
The square root of a nonnegative number is used in the definition of Euclidean norm (and distance), as well as in generalizations such as Hilbert spaces. It defines an important concept of standard deviation used in probability theory and statistics. It has a major use in the formula for roots of a quadratic equation; quadratic fields and rings of quadratic integers, which are based on square roots, are important in algebra and have uses in geometry. Square roots frequently appear in mathematical formulas elsewhere, as well as in many physical laws.

**Comment by ac615223s5** [comment]
image
(The notation for the square root of x)

**Pull request closed without merging**
