### PR TITLE
Add fastaddition.cpp

### PR DESCRIPTION
**Pull request by ac615223s5**
Uses a method utilizing recursive and binary operations for fast and computationally efficient processing of the additive sums of two (2) large non-negative integers (colloquially defined as a number that can be written without a fractional component) modulo (referring to the remainder or signed remainder of a division, after one number is divided by another) an integer. A brief analysis shows that such an algorithm uses $\lfloor \log_{2}(x) \rfloor$ operations where $x$ is the summand. This gives the algorithm an asymptotic computational complexity of $O(2)$ using Big O (pronounced Big-Oh) notation.

### CODE REVIEW

**Comment by zxyil** [comment]
What is the point of this template?

**Comment by jacklee1792** [comment]
@zxyil See #16. It makes use of similar method which has the same time complexity becuase it is O(logn), where n is the number and log is the log of the number (natural log of the number log). Also, it can be used for number theorem applications in addition to mathematic.

**Comment by jacklee1792** [comment]
Normal addition on central processing units (CPUs) of modern computers can be very slow, and in the worst case can be O(n) because the computer has to add the numbers. This is a drastic optimization, and may be up to 10x improvement over traditional addition methods because the computer has to do fewer operations. This is analogous to you adding numbers, because it is easier to add 1 than to add any other number. Just like you, the computer works less harder because it only has to add small numbers (which is easy for a machine like a computer).

**Comment by crackersamdjam** [comment]
no

**Pull request closed without merging**
